/* eslint-disable */

// -----------------------------------------------------------------------------------------
// This file is automatically generated by the MagnusOpera OpenApiGen TypeScript client generator.
// Do not modify this file directly. Any changes will be overwritten.
// -----------------------------------------------------------------------------------------

import type { AxiosInstance } from "axios"

// === get /Catalog/dashboard ===
export type CatalogDashboardGet200Response = {
    owner: {
        id: string
        firstName: string
        lastName: string
        nickname?: null | string
        state?: "Draft" | "Active" | "Archived"
        createdAt?: string
        nextReviewOn?: null | string
        labels?: null | {
            [key: string]: string
        }
    }
    state?: "Draft" | "Active" | "Archived"
    tags: Array<string>
    metrics: {
        [key: string]: {
            value?: number
            unit?: null | string
        }
    }
    primaryPet: {
        kind: "cat"
        livesLeft?: number
        name: string
    } | {
        kind: "dog"
        goodBoy?: boolean
        name: string
    }
    backupPet?: null | {
        kind: "cat"
        livesLeft?: number
        name: string
    } | {
        kind: "dog"
        goodBoy?: boolean
        name: string
    }
}
export type CatalogDashboardGet0Response = {
    type?: null | string
    title?: null | string
    status?: null | number
    detail?: null | string
    instance?: null | string
}
export async function getCatalogDashboard(axios: AxiosInstance): Promise<[200, CatalogDashboardGet200Response] | [0, CatalogDashboardGet0Response]> {
    const __queryString__ = "";
    const __headers__: Record<string, string> = {};
    const __response__ = await axios.request({
        method: "get",
        url: `/Catalog/dashboard${__queryString__}`,
        headers: __headers__,
        validateStatus: () => true,
    });
    switch (__response__.status) {
        case 200: return [200, __response__.data as CatalogDashboardGet200Response]
        default: return [0, __response__.data as CatalogDashboardGet0Response]
    }
}

// === post /Catalog/adoptions ===
export type CatalogAdoptionsPostRequest = {
    pet: {
        kind: "cat"
        livesLeft?: number
        name: string
    } | {
        kind: "dog"
        goodBoy?: boolean
        name: string
    }
    notes?: null | string
    labels?: null | Array<string>
}
export type CatalogAdoptionsPost201Response = {
    id: string
    pet: {
        kind: "cat"
        livesLeft?: number
        name: string
    } | {
        kind: "dog"
        goodBoy?: boolean
        name: string
    }
    createdAt?: string
}
export type CatalogAdoptionsPost409Response = {
    type?: null | string
    title?: null | string
    status?: null | number
    detail?: null | string
    instance?: null | string
}
export type CatalogAdoptionsPost0Response = {
    type?: null | string
    title?: null | string
    status?: null | number
    detail?: null | string
    instance?: null | string
}
export async function postCatalogAdoptions(axios: AxiosInstance, request: CatalogAdoptionsPostRequest): Promise<[201, CatalogAdoptionsPost201Response] | [409, CatalogAdoptionsPost409Response] | [0, CatalogAdoptionsPost0Response]> {
    const __queryString__ = "";
    const __headers__: Record<string, string> = {};
    __headers__["Content-Type"] = "application/json";
    const __response__ = await axios.request({
        method: "post",
        url: `/Catalog/adoptions${__queryString__}`,
        data: JSON.stringify(request),
        headers: __headers__,
        validateStatus: () => true,
    });
    switch (__response__.status) {
        case 201: return [201, __response__.data as CatalogAdoptionsPost201Response]
        case 409: return [409, __response__.data as CatalogAdoptionsPost409Response]
        default: return [0, __response__.data as CatalogAdoptionsPost0Response]
    }
}

