/* eslint-disable */

// -----------------------------------------------------------------------------------------
// This file is automatically generated by the MagnusOpera OpenApiGen TypeScript client generator.
// Do not modify this file directly. Any changes will be overwritten.
// -----------------------------------------------------------------------------------------

import type { AxiosInstance } from "axios"

// === post /Diagnostics/echo ===
export type DiagnosticsEchoPostRequest = string
export type DiagnosticsEchoPost200Response = string
export type DiagnosticsEchoPost400Response = {
    type?: null | string
    title?: null | string
    status?: null | number
    detail?: null | string
    instance?: null | string
}
export async function postDiagnosticsEcho(axios: AxiosInstance, request: DiagnosticsEchoPostRequest): Promise<[200, DiagnosticsEchoPost200Response] | [400, DiagnosticsEchoPost400Response]> {
    const __queryString__ = "";
    const __headers__: Record<string, string> = {};
    __headers__["Content-Type"] = "text/plain";
    const __response__ = await axios.request({
        method: "POST",
        url: `/Diagnostics/echo${__queryString__}`,
        data: request,
        headers: __headers__,
        validateStatus: () => true,
    });
    switch (__response__.status) {
        case 200: return [200, __response__.data as DiagnosticsEchoPost200Response]
        case 400: return [400, __response__.data as DiagnosticsEchoPost400Response]
        default: throw Error(`Unexpected status ${__response__.status}`)
    }
}

// === delete /Diagnostics/cache/{key} ===
export type DiagnosticsCacheKeyDelete204Response = void
export type DiagnosticsCacheKeyDelete0Response = {
    type?: null | string
    title?: null | string
    status?: null | number
    detail?: null | string
    instance?: null | string
}
export async function deleteDiagnosticsCacheKey(axios: AxiosInstance, key: string): Promise<[204, DiagnosticsCacheKeyDelete204Response] | [0, DiagnosticsCacheKeyDelete0Response]> {
    const __queryString__ = "";
    const __headers__: Record<string, string> = {};
    const __response__ = await axios.request({
        method: "DELETE",
        url: `/Diagnostics/cache/${key}${__queryString__}`,
        headers: __headers__,
        validateStatus: () => true,
    });
    switch (__response__.status) {
        case 204: return [204, undefined as DiagnosticsCacheKeyDelete204Response]
        default: return [0, __response__.data as DiagnosticsCacheKeyDelete0Response]
    }
}
