/* eslint-disable */

// -----------------------------------------------------------------------------------------
// This file is automatically generated by the MagnusOpera OpenApiGen TypeScript client generator.
// Do not modify this file directly. Any changes will be overwritten.
// -----------------------------------------------------------------------------------------

import type { AxiosInstance } from "axios"

// === post /Files/upload ===
export type FilesUploadPostRequest = {
    file?: Blob
    description?: string
}
export type FilesUploadPost200Response = {
    id: string
    fileName: string
    metadata?: null | {
        [key: string]: string
    }
}
export type FilesUploadPost400Response = {
    type?: null | string
    title?: null | string
    status?: null | number
    detail?: null | string
    instance?: null | string
}
export type FilesUploadPost0Response = {
    type?: null | string
    title?: null | string
    status?: null | number
    detail?: null | string
    instance?: null | string
}
export async function postFilesUpload(axios: AxiosInstance, request: FilesUploadPostRequest): Promise<[200, FilesUploadPost200Response] | [400, FilesUploadPost400Response] | [0, FilesUploadPost0Response]> {
    const __queryString__ = "";
    const __form__ = new FormData();
    if (request.file !== undefined) __form__.append("File", request.file);
    if (request.description !== undefined) __form__.append("Description", request.description);
    const __headers__: Record<string, string> = {};
    const __response__ = await axios.request({
        method: "post",
        url: `/Files/upload${__queryString__}`,
        data: __form__,
        headers: __headers__,
        validateStatus: () => true,
    });
    switch (__response__.status) {
        case 200: return [200, __response__.data as FilesUploadPost200Response]
        case 400: return [400, __response__.data as FilesUploadPost400Response]
        default: return [0, __response__.data as FilesUploadPost0Response]
    }
}

// === get /Files/{id}/content ===
export type FilesIdContentGet200Response = Blob
export type FilesIdContentGet404Response = {
    type?: null | string
    title?: null | string
    status?: null | number
    detail?: null | string
    instance?: null | string
}
export async function getFilesIdContent(axios: AxiosInstance, id: string): Promise<[200, FilesIdContentGet200Response] | [404, FilesIdContentGet404Response]> {
    const __queryString__ = "";
    const __headers__: Record<string, string> = {};
    const __response__ = await axios.request({
        method: "get",
        url: `/Files/${id}/content${__queryString__}`,
        headers: __headers__,
        validateStatus: () => true,
        responseType: "blob",
    });
    switch (__response__.status) {
        case 200: return [200, __response__.data as FilesIdContentGet200Response]
        case 404: return [404, __response__.data as FilesIdContentGet404Response]
        default: throw Error(`Unexpected status ${__response__.status}`)
    }
}

