/* eslint-disable */

// -----------------------------------------------------------------------------------------
// This file is automatically generated by the MagnusOpera OpenApiGen TypeScript client generator.
// Do not modify this file directly. Any changes will be overwritten.
// -----------------------------------------------------------------------------------------

import type { AxiosInstance } from "axios"

// === get /pets ===
export type PetsGet200Response = Array<{
    id: number
    name: string
    tag?: string
}>
export type PetsGet0Response = {
    code: number
    message: string
}
export async function getPets(axios: AxiosInstance, limit?: number): Promise<[200, PetsGet200Response] | [0, PetsGet0Response]> {
    const __query__: string[] = [];
    if (limit !== undefined) __query__.push(`limit=${encodeURIComponent(limit)}`);
    const __queryString__ = __query__.length ? `?${__query__.join("&")}` : "";
    const __headers__: Record<string, string> = {};
    const __response__ = await axios.request({
        method: "get",
        url: `/pets${__queryString__}`,
        headers: __headers__,
        validateStatus: () => true,
    });
    switch (__response__.status) {
        case 200: return [200, __response__.data as PetsGet200Response]
        default: return [0, __response__.data as PetsGet0Response]
    }
}

// === post /pets ===
export type PetsPost201Response = void
export type PetsPost0Response = {
    code: number
    message: string
}
export async function postPets(axios: AxiosInstance): Promise<[201, PetsPost201Response] | [0, PetsPost0Response]> {
    const __queryString__ = "";
    const __headers__: Record<string, string> = {};
    const __response__ = await axios.request({
        method: "post",
        url: `/pets${__queryString__}`,
        headers: __headers__,
        validateStatus: () => true,
    });
    switch (__response__.status) {
        case 201: return [201, undefined as PetsPost201Response]
        default: return [0, __response__.data as PetsPost0Response]
    }
}

// === get /pets/{petId} ===
export type PetsPetidGet200Response = {
    id: number
    name: string
    tag?: string
}
export type PetsPetidGet0Response = {
    code: number
    message: string
}
export async function getPetsPetid(axios: AxiosInstance, petId: string): Promise<[200, PetsPetidGet200Response] | [0, PetsPetidGet0Response]> {
    const __queryString__ = "";
    const __headers__: Record<string, string> = {};
    const __response__ = await axios.request({
        method: "get",
        url: `/pets/${petId}${__queryString__}`,
        headers: __headers__,
        validateStatus: () => true,
    });
    switch (__response__.status) {
        case 200: return [200, __response__.data as PetsPetidGet200Response]
        default: return [0, __response__.data as PetsPetidGet0Response]
    }
}

