/* eslint-disable */

// -----------------------------------------------------------------------------------------
// This file is automatically generated by the MagnusOpera OpenApiGen TypeScript client generator.
// Do not modify this file directly. Any changes will be overwritten.
// -----------------------------------------------------------------------------------------

async function __readJson__(response: Response): Promise<unknown> {
    const __text__ = await response.text();
    return __text__ ? JSON.parse(__text__) : undefined;
}

// === get /pets ===
export type PetsGet200Response = Array<{
    id: number
    name: string
    tag?: string
}>
export type PetsGet0Response = {
    code: number
    message: string
}
export async function getPets(fetcher: typeof fetch, limit?: number): Promise<[200, PetsGet200Response] | [0, PetsGet0Response]> {
    const __query__: string[] = [];
    if (limit !== undefined) __query__.push(`limit=${encodeURIComponent(limit)}`);
    const __queryString__ = __query__.length ? `?${__query__.join("&")}` : "";
    const __headers__: Record<string, string> = {};
    const __requestInit__: RequestInit = {
        method: "get",
        headers: __headers__,
    };
    const __response__ = await fetcher(`/pets${__queryString__}`, __requestInit__);
    switch (__response__.status) {
        case 200: return [200, (await __readJson__(__response__)) as PetsGet200Response]
        default: return [0, (await __readJson__(__response__)) as PetsGet0Response]
    }
}

// === post /pets ===
export type PetsPost201Response = void
export type PetsPost0Response = {
    code: number
    message: string
}
export async function postPets(fetcher: typeof fetch): Promise<[201, PetsPost201Response] | [0, PetsPost0Response]> {
    const __queryString__ = "";
    const __headers__: Record<string, string> = {};
    const __requestInit__: RequestInit = {
        method: "post",
        headers: __headers__,
    };
    const __response__ = await fetcher(`/pets${__queryString__}`, __requestInit__);
    switch (__response__.status) {
        case 201: return [201, undefined as PetsPost201Response]
        default: return [0, (await __readJson__(__response__)) as PetsPost0Response]
    }
}

// === get /pets/{petId} ===
export type PetsPetidGet200Response = {
    id: number
    name: string
    tag?: string
}
export type PetsPetidGet0Response = {
    code: number
    message: string
}
export async function getPetsPetid(fetcher: typeof fetch, petId: string): Promise<[200, PetsPetidGet200Response] | [0, PetsPetidGet0Response]> {
    const __queryString__ = "";
    const __headers__: Record<string, string> = {};
    const __requestInit__: RequestInit = {
        method: "get",
        headers: __headers__,
    };
    const __response__ = await fetcher(`/pets/${petId}${__queryString__}`, __requestInit__);
    switch (__response__.status) {
        case 200: return [200, (await __readJson__(__response__)) as PetsPetidGet200Response]
        default: return [0, (await __readJson__(__response__)) as PetsPetidGet0Response]
    }
}

