using System.Text;
using System.Text.RegularExpressions;

namespace OpenApiGen.Generators;

public abstract partial class TypeScriptHttpClientGenerator(Dictionary<string, Schema> components) {
    protected const int IndentationSize = 4;

    private readonly Dictionary<string, string> _replacedSchemas = [];

    public void Generate(OpenApiDocument document, string outputPath) {
        var tags = new Dictionary<string, List<(Operation operation, string path, string method)>>();
        foreach (var (path, pathItem) in document.Paths) {
            if (pathItem.Get is not null) {
                Add(tags, pathItem.Get, path, "get");
            }

            if (pathItem.Post is not null) {
                Add(tags, pathItem.Post, path, "post");
            }

            if (pathItem.Put is not null) {
                Add(tags, pathItem.Put, path, "put");
            }

            if (pathItem.Delete is not null) {
                Add(tags, pathItem.Delete, path, "delete");
            }

            if (pathItem.Patch is not null) {
                Add(tags, pathItem.Patch, path, "patch");
            }
        }

        var bearerRequirement =
            document.Components?.SecuritySchemes?.Where(x => x.Value is HttpSecurityScheme { Scheme: "bearer" })
                .Select(x => x.Key).FirstOrDefault();

        var indexContent = new StringBuilder();
        AppendFileHeader(indexContent);

        foreach (var (tag, operations) in tags) {
            var sb = new StringBuilder();
            var outputFilename = Path.Combine(outputPath, $"{tag}.ts");
            indexContent.AppendLine($"export * from './{tag}'");

            AppendFileHeader(sb);
            AppendTransportPreamble(sb);

            foreach (var (operation, path, method) in operations) {
                AppendOperation(
                    sb,
                    operation,
                    path,
                    method,
                    hasBearer: bearerRequirement is not null && operation.Security?.Any(x => x.ContainsKey(bearerRequirement)) == true
                );
            }

            File.WriteAllText(outputFilename, sb.ToString());
        }

        File.WriteAllText(Path.Combine(outputPath, "index.ts"), indexContent.ToString());

        foreach (var (source, target) in _replacedSchemas) {
            Console.WriteLine($"WARNING: component {source} replaced with {target}");
        }
    }

    protected abstract void AppendTransportPreamble(StringBuilder sb);

    protected abstract string ClientParameterDeclaration { get; }

    protected abstract void AppendTransportRequest(StringBuilder sb, OperationRenderContext context);

    protected abstract string GetResponseValueExpression(ResponseRenderContext response);

    private static void AppendFileHeader(StringBuilder sb) {
        sb.AppendLine("/* eslint-disable */");
        sb.AppendLine("");
        sb.AppendLine("// -----------------------------------------------------------------------------------------");
        sb.AppendLine("// This file is automatically generated by the MagnusOpera OpenApiGen TypeScript client generator.");
        sb.AppendLine("// Do not modify this file directly. Any changes will be overwritten.");
        sb.AppendLine("// -----------------------------------------------------------------------------------------");
        sb.AppendLine("");
    }

    private void AppendOperation(StringBuilder sb, Operation operation, string path, string method, bool hasBearer) {
        sb.AppendLine($"// === {method} {path} ===");

        var functionName = GenerateFunctionName(path, method);
        var interfaceBaseName = GenerateInterfaceName(path, method);

        var request = BuildRequestRenderContext(operation.RequestBody, method, path, interfaceBaseName);
        if (request.TypeName is not null) {
            sb.Append($"export type {request.TypeName} = ");
            sb.AppendLine(GenerateType(IndentationSize, request.Schema ?? new PrimitiveSchema(), [], []));
        }

        var responses = BuildResponseRenderContexts(operation.Responses, method, path, interfaceBaseName);
        foreach (var response in responses) {
            if (response.BodyKind == ResponseBodyKind.Binary) {
                sb.AppendLine($"export type {response.TypeName} = Blob");
                continue;
            }

            sb.Append($"export type {response.TypeName} = ");
            sb.AppendLine(GenerateType(IndentationSize, response.Schema ?? new PrimitiveSchema(), [], []));
        }

        var pathParameters = operation.Parameters?.Where(x => x.In != "query").ToList() ?? [];
        var queryParameters = operation.Parameters?.Where(x => x.In == "query").ToList() ?? [];
        var functionParameters = new List<string> { ClientParameterDeclaration };
        if (hasBearer) {
            functionParameters.Add("bearer: string");
        }
        functionParameters.AddRange(pathParameters.Select(ParameterPrototype));
        if (request.TypeName is not null) {
            functionParameters.Add($"request: {request.TypeName}");
        }
        functionParameters.AddRange(queryParameters.Select(ParameterPrototype));

        var unionType = string.Join(" | ", responses.Select(response => response.UnionMember));
        sb.AppendLine($"export async function {functionName}({string.Join(", ", functionParameters)}): Promise<{unionType}> {{");

        if (queryParameters.Count > 0) {
            sb.Append(' ', IndentationSize); sb.AppendLine("const __query__: string[] = [];");
            foreach (var parameter in queryParameters) {
                sb.Append(' ', IndentationSize); sb.AppendLine(ParameterQueryInitializer(parameter));
            }
            sb.Append(' ', IndentationSize); sb.AppendLine("const __queryString__ = __query__.length ? `?${__query__.join(\"&\")}` : \"\";");
        } else {
            sb.Append(' ', IndentationSize); sb.AppendLine("const __queryString__ = \"\";");
        }

        if (request.BodyKind == RequestBodyKind.Multipart) {
            sb.Append(' ', IndentationSize); sb.AppendLine("const __form__ = new FormData();");
            foreach (var (propertyName, _) in request.MultipartSchema?.Properties ?? []) {
                var accessor = $"request.{ToFieldName(propertyName)}";
                sb.Append(' ', IndentationSize); sb.AppendLine($"if ({accessor} !== undefined) __form__.append(\"{propertyName}\", {accessor});");
            }
        }

        var context = new OperationRenderContext(method, path, hasBearer, request.BodyKind, responses.Any(x => x.BodyKind == ResponseBodyKind.Binary));
        AppendTransportRequest(sb, context);

        sb.Append(' ', IndentationSize); sb.AppendLine("switch (__response__.status) {");
        foreach (var response in responses.Where(x => !x.IsDefault)) {
            sb.Append(' ', IndentationSize * 2);
            sb.AppendLine($"case {response.StatusCode}: return [{response.StatusCode}, {GetResponseValueExpression(response)}]");
        }

        var defaultResponse = responses.FirstOrDefault(x => x.IsDefault);
        if (defaultResponse is not null) {
            sb.Append(' ', IndentationSize * 2);
            sb.AppendLine($"default: return [0, {GetResponseValueExpression(defaultResponse)}]");
        } else {
            sb.Append(' ', IndentationSize * 2); sb.AppendLine("default: throw Error(`Unexpected status ${__response__.status}`)");
        }

        sb.Append(' ', IndentationSize); sb.AppendLine("}");
        sb.AppendLine("}");
        sb.AppendLine();
    }

    private RequestRenderContext BuildRequestRenderContext(RequestBody? requestBody, string method, string path, string interfaceBaseName) {
        if (requestBody is null) {
            return new RequestRenderContext(RequestBodyKind.None, null, null, null);
        }

        if (TryGetJsonMediaType(requestBody.Content, out var requestContent)) {
            return new RequestRenderContext(
                RequestBodyKind.Json,
                $"{interfaceBaseName}Request",
                requestContent.Schema ?? new PrimitiveSchema(),
                null
            );
        }

        if (requestBody.Content.TryGetValue("text/plain", out requestContent)) {
            return new RequestRenderContext(
                RequestBodyKind.Text,
                $"{interfaceBaseName}Request",
                requestContent.Schema ?? new PrimitiveSchema(),
                null
            );
        }

        if (requestBody.Content.TryGetValue("multipart/form-data", out requestContent)) {
            return new RequestRenderContext(
                RequestBodyKind.Multipart,
                $"{interfaceBaseName}Request",
                requestContent.Schema ?? new PrimitiveSchema(),
                requestContent.Schema as ObjectSchema
            );
        }

        throw new ApplicationException($"Operation {method} {path} has an unhandled request type: {requestBody.Content.Keys.FirstOrDefault()}");
    }

    private List<ResponseRenderContext> BuildResponseRenderContexts(
        Dictionary<string, Response> responses,
        string method,
        string path,
        string interfaceBaseName
    ) {
        var renderedResponses = new List<ResponseRenderContext>();

        foreach (var (responseType, response) in responses) {
            var statusCode = responseType == "default" ? "0" : responseType;
            var typeName = $"{interfaceBaseName}{statusCode}Response";

            if (TryGetJsonMediaType(response.Content, out var responseContent)) {
                renderedResponses.Add(new ResponseRenderContext(
                    responseType,
                    typeName,
                    ResponseBodyKind.Json,
                    responseContent.Schema ?? new PrimitiveSchema()
                ));
                continue;
            }

            if (response.Content?.TryGetValue("text/plain", out responseContent) == true) {
                renderedResponses.Add(new ResponseRenderContext(
                    responseType,
                    typeName,
                    ResponseBodyKind.Text,
                    responseContent.Schema ?? new PrimitiveSchema()
                ));
                continue;
            }

            if (response.Content is null || response.Content.Count == 0) {
                renderedResponses.Add(new ResponseRenderContext(
                    responseType,
                    typeName,
                    ResponseBodyKind.None,
                    new PrimitiveSchema()
                ));
                continue;
            }

            renderedResponses.Add(new ResponseRenderContext(
                responseType,
                typeName,
                ResponseBodyKind.Binary,
                null
            ));
        }

        return renderedResponses;
    }

    private string ParameterPrototype(Parameter param) {
        var tsType = GenerateType(0, param.Schema, [], []);
        var optional = param.Required != true ? "?" : "";
        return $"{param.Name}{optional}: {tsType}";
    }

    private static string ParameterQueryInitializer(Parameter param) {
        return $"if ({param.Name} !== undefined) __query__.push(`{param.Name}=${{encodeURIComponent({param.Name})}}`);";
    }

    private static bool TryGetJsonMediaType(Dictionary<string, MediaType>? content, out MediaType mediaType) {
        mediaType = null!;
        if (content is null || content.Count == 0) {
            return false;
        }

        if (content.TryGetValue("application/json", out var exactMediaType) && exactMediaType is not null) {
            mediaType = exactMediaType;
            return true;
        }

        foreach (var (contentType, candidate) in content) {
            if (contentType == "text/json" || contentType.EndsWith("+json", StringComparison.OrdinalIgnoreCase)) {
                mediaType = candidate;
                return true;
            }
        }

        return false;
    }

    private static void Add(Dictionary<string, List<(Operation, string, string)>> dict, Operation operation, string path, string method) {
        var tag = operation.Tags.FirstOrDefault() ?? "Default";
        if (!dict.TryGetValue(tag, out var value)) {
            value = [];
            dict[tag] = value;
        }

        value.Add((operation, path, method));
    }

    private string RawGenerateType(int indent, Schema schema, string[] composedRequired, Dictionary<string, Schema> composedProperties) {
        if (schema is RefSchema refSchema) {
            var componentName = refSchema.Ref.Split("/").Last();
            var componentSchema = components[componentName];
            return GenerateType(indent, componentSchema, composedRequired, composedProperties);
        }

        if (schema is ComposedSchema composedSchema) {
            string[] variantComposedRequired = [.. composedRequired, .. composedSchema.Required ?? []];
            Dictionary<string, Schema> variantComposedProperties = new([.. composedProperties, .. composedSchema.Properties ?? []]);
            var composed = composedSchema.AnyOf ?? composedSchema.OneOf ?? [];
            var variants = string.Join(" | ", composed.Select(variant => GenerateType(indent, variant, variantComposedRequired, variantComposedProperties)));
            return variants;
        }

        if (schema is ArraySchema arraySchema) {
            return $"Array<{GenerateType(indent, arraySchema.Items, [], [])}>";
        }

        if (schema is ObjectSchema objectSchema) {
            var sb = new StringBuilder();
            sb.AppendLine("{");
            string[] required = [.. composedRequired, .. objectSchema.Required ?? []];
            Dictionary<string, Schema> properties = new([.. composedProperties, .. objectSchema.Properties ?? []]);
            foreach (var (name, property) in properties) {
                var optional = required.Contains(name) ? "" : "?";
                var type = GenerateType(indent + IndentationSize, property, [], []);
                sb.Append(' ', indent);
                sb.AppendLine($"{ToFieldName(name)}{optional}: {type}");
            }

            if (objectSchema.AdditionalProperties is not null) {
                var mapValueType = GenerateType(indent + IndentationSize, objectSchema.AdditionalProperties, [], []);
                sb.Append(' ', indent);
                sb.AppendLine($"[key: string]: {mapValueType}");
            }

            sb.Append(' ', indent - IndentationSize);
            sb.Append('}');
            return sb.ToString();
        }

        if (schema is EnumSchema enumSchema) {
            return string.Join(" | ", enumSchema.Enum.Where(value => value is not null).Select(value => $"\"{value}\""));
        }

        if (schema is PrimitiveSchema primitiveSchema) {
            var types = primitiveSchema.Type ?? ["void"];
            return string.Join(" | ", types.Select(type => (type, primitiveSchema.Format) switch {
                ("string", "binary") => "Blob",
                ("string", _) => "string",
                ("integer", _) => "number",
                ("number", _) => "number",
                ("boolean", _) => "boolean",
                ("null", _) => "null",
                ("void", "date") => "string",
                ("void", "date-time") => "string",
                _ => "void"
            }));
        }

        throw new ApplicationException("Unknown schema type.");
    }

    private string GenerateType(int indent, Schema schema, string[] composedRequired, Dictionary<string, Schema> composedProperties) {
        var type = RawGenerateType(indent, schema, composedRequired, composedProperties);
        return schema.Nullable == true ? $"null | {type}" : type;
    }

    private static string GenerateFunctionName(string path, string method) {
        var parts = path.Trim('/').Split('/', StringSplitOptions.RemoveEmptyEntries)
            .Select(part => IdentifierRegex().Replace(part, ""))
            .Select(Capitalize);
        return method + string.Concat(parts);
    }

    private static string GenerateInterfaceName(string path, string method) {
        var parts = path.Trim('/').Split('/', StringSplitOptions.RemoveEmptyEntries)
            .Select(part => IdentifierRegex().Replace(part, ""))
            .Select(Capitalize);
        return string.Concat(parts) + Capitalize(method);
    }

    protected static string ToTemplateString(string path) =>
        TemplateRegex().Replace(path, @"${$1}");

    protected static string ToFieldName(string name) {
        name = IdentifierRegex().Replace(name, "");
        return Lowerize(name);
    }

    private static string Capitalize(string value) =>
        string.IsNullOrEmpty(value) ? value : char.ToUpperInvariant(value[0]) + value[1..].ToLowerInvariant();

    private static string Lowerize(string value) =>
        string.IsNullOrEmpty(value) ? value : char.ToLowerInvariant(value[0]) + value[1..];

    protected sealed record OperationRenderContext(
        string Method,
        string Path,
        bool HasBearer,
        RequestBodyKind RequestBodyKind,
        bool HasBinaryResponse
    );

    protected sealed record ResponseRenderContext(
        string StatusCode,
        string TypeName,
        ResponseBodyKind BodyKind,
        Schema? Schema
    ) {
        public bool IsDefault => StatusCode == "default";

        public string UnionMember => $"[{(IsDefault ? "0" : StatusCode)}, {TypeName}]";
    }

    private sealed record RequestRenderContext(
        RequestBodyKind BodyKind,
        string? TypeName,
        Schema? Schema,
        ObjectSchema? MultipartSchema
    );

    protected enum RequestBodyKind {
        None,
        Json,
        Text,
        Multipart
    }

    protected enum ResponseBodyKind {
        None,
        Json,
        Text,
        Binary
    }

    [GeneratedRegex("[^a-zA-Z0-9]")]
    private static partial Regex IdentifierRegex();

    [GeneratedRegex(@"\{([^\}]+)\}")]
    private static partial Regex TemplateRegex();
}
