/* eslint-disable */

// -----------------------------------------------------------------------------------------
// This file is automatically generated by the MagnusOpera OpenApiGen TypeScript client generator.
// Do not modify this file directly. Any changes will be overwritten.
// -----------------------------------------------------------------------------------------

export async function __readJson__(response: Response): Promise<unknown> {
    const __text__ = await response.text();
    return __text__ ? JSON.parse(__text__) : undefined;
}
