/* eslint-disable */

// -----------------------------------------------------------------------------------------
// This file is automatically generated by the MagnusOpera OpenApiGen TypeScript client generator.
// Do not modify this file directly. Any changes will be overwritten.
// -----------------------------------------------------------------------------------------

import { __readJson__ } from "./_fetch"

// === post /Diagnostics/echo ===
export type DiagnosticsEchoPostRequest = string
export type DiagnosticsEchoPost200Response = string
export type DiagnosticsEchoPost400Response = {
    type?: null | string
    title?: null | string
    status?: null | number
    detail?: null | string
    instance?: null | string
}
export async function postDiagnosticsEcho(fetcher: typeof fetch, request: DiagnosticsEchoPostRequest): Promise<[200, DiagnosticsEchoPost200Response] | [400, DiagnosticsEchoPost400Response]> {
    const __queryString__ = "";
    const __headers__: Record<string, string> = {};
    __headers__["Content-Type"] = "text/plain";
    const __requestInit__: RequestInit = {
        method: "post",
        headers: __headers__,
        body: request,
    };
    const __response__ = await fetcher(`/Diagnostics/echo${__queryString__}`, __requestInit__);
    switch (__response__.status) {
        case 200: return [200, (await __response__.text()) as DiagnosticsEchoPost200Response]
        case 400: return [400, (await __readJson__(__response__)) as DiagnosticsEchoPost400Response]
        default: throw Error(`Unexpected status ${__response__.status}`)
    }
}

// === delete /Diagnostics/cache/{key} ===
export type DiagnosticsCacheKeyDelete204Response = void
export type DiagnosticsCacheKeyDelete0Response = {
    type?: null | string
    title?: null | string
    status?: null | number
    detail?: null | string
    instance?: null | string
}
export async function deleteDiagnosticsCacheKey(fetcher: typeof fetch, key: string): Promise<[204, DiagnosticsCacheKeyDelete204Response] | [0, DiagnosticsCacheKeyDelete0Response]> {
    const __queryString__ = "";
    const __headers__: Record<string, string> = {};
    const __requestInit__: RequestInit = {
        method: "delete",
        headers: __headers__,
    };
    const __response__ = await fetcher(`/Diagnostics/cache/${key}${__queryString__}`, __requestInit__);
    switch (__response__.status) {
        case 204: return [204, undefined as DiagnosticsCacheKeyDelete204Response]
        default: return [0, (await __readJson__(__response__)) as DiagnosticsCacheKeyDelete0Response]
    }
}

