/* eslint-disable */

// -----------------------------------------------------------------------------------------
// This file is automatically generated by the MagnusOpera OpenApiGen TypeScript client generator.
// Do not modify this file directly. Any changes will be overwritten.
// -----------------------------------------------------------------------------------------

import { __readJson__ } from "./_fetch"

// === get /User ===
export type UserGet200Response = Array<{
    id: string
    firstName: string
    lastName: string
    nickname?: null | string
    state?: "Draft" | "Active" | "Archived"
    createdAt?: string
    nextReviewOn?: null | string
    labels?: null | {
        [key: string]: string
    }
}>
export type UserGet400Response = {
    type?: null | string
    title?: null | string
    status?: null | number
    detail?: null | string
    instance?: null | string
}
export async function getUser(fetcher: typeof fetch, skip?: number, limit?: number): Promise<[200, UserGet200Response] | [400, UserGet400Response]> {
    const __query__: string[] = [];
    if (skip !== undefined) __query__.push(`skip=${encodeURIComponent(skip)}`);
    if (limit !== undefined) __query__.push(`limit=${encodeURIComponent(limit)}`);
    const __queryString__ = __query__.length ? `?${__query__.join("&")}` : "";
    const __headers__: Record<string, string> = {};
    const __requestInit__: RequestInit = {
        method: "get",
        headers: __headers__,
    };
    const __response__ = await fetcher(`/User${__queryString__}`, __requestInit__);
    switch (__response__.status) {
        case 200: return [200, (await __readJson__(__response__)) as UserGet200Response]
        case 400: return [400, (await __readJson__(__response__)) as UserGet400Response]
        default: throw Error(`Unexpected status ${__response__.status}`)
    }
}

// === post /User/hello-world ===
export type UserHelloworldPostRequest = {
    firstName: string
    lastName?: null | string
}
export type UserHelloworldPost200Response = {
    message: string
}
export type UserHelloworldPost400Response = {
    type?: null | string
    title?: null | string
    status?: null | number
    detail?: null | string
    instance?: null | string
}
export async function postUserHelloworld(fetcher: typeof fetch, request: UserHelloworldPostRequest): Promise<[200, UserHelloworldPost200Response] | [400, UserHelloworldPost400Response]> {
    const __queryString__ = "";
    const __headers__: Record<string, string> = {};
    __headers__["Content-Type"] = "application/json";
    const __requestInit__: RequestInit = {
        method: "post",
        headers: __headers__,
        body: JSON.stringify(request),
    };
    const __response__ = await fetcher(`/User/hello-world${__queryString__}`, __requestInit__);
    switch (__response__.status) {
        case 200: return [200, (await __readJson__(__response__)) as UserHelloworldPost200Response]
        case 400: return [400, (await __readJson__(__response__)) as UserHelloworldPost400Response]
        default: throw Error(`Unexpected status ${__response__.status}`)
    }
}

// === patch /User/{id} ===
export type UserIdPatchRequest = {
    firstName?: null | string
    lastName?: null | string
    nickname?: null | string
    labels?: null | {
        [key: string]: string
    }
}
export type UserIdPatch200Response = {
    id: string
    firstName: string
    lastName: string
    nickname?: null | string
    state?: "Draft" | "Active" | "Archived"
    createdAt?: string
    nextReviewOn?: null | string
    labels?: null | {
        [key: string]: string
    }
}
export type UserIdPatch400Response = {
    type?: null | string
    title?: null | string
    status?: null | number
    detail?: null | string
    instance?: null | string
}
export type UserIdPatch404Response = {
    type?: null | string
    title?: null | string
    status?: null | number
    detail?: null | string
    instance?: null | string
}
export async function patchUserId(fetcher: typeof fetch, bearer: string, id: string, request: UserIdPatchRequest): Promise<[200, UserIdPatch200Response] | [400, UserIdPatch400Response] | [404, UserIdPatch404Response]> {
    const __queryString__ = "";
    const __headers__: Record<string, string> = {};
    __headers__.Authorization = `Bearer ${bearer}`;
    __headers__["Content-Type"] = "application/json";
    const __requestInit__: RequestInit = {
        method: "patch",
        headers: __headers__,
        body: JSON.stringify(request),
    };
    const __response__ = await fetcher(`/User/${id}${__queryString__}`, __requestInit__);
    switch (__response__.status) {
        case 200: return [200, (await __readJson__(__response__)) as UserIdPatch200Response]
        case 400: return [400, (await __readJson__(__response__)) as UserIdPatch400Response]
        case 404: return [404, (await __readJson__(__response__)) as UserIdPatch404Response]
        default: throw Error(`Unexpected status ${__response__.status}`)
    }
}

